
[workspace]
members = [ "broccoli","demo-web","report/data-gen","analysis/float-vs-integer","analysis/rebal-vs-query","analysis/par-tuner","analysis/layout","analysis/support","analysis/plot-gen","analysis/colfind","analysis/levels"]
