[package]
name = "broccoli"
version = "2.2.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
description = "broadphase collision detection algorithms"
license = "MIT"
repository = "https://github.com/tiby312/broccoli"
keywords = ["tree", "kdtree","broadphase","space-partitioning","no_std"]
readme = "README.md"
edition = "2018"
include = ["src/**/*", "LICENSE-MIT", "README.md"]

[features]
default = ["use_rayon"]
use_rayon = ["rayon-core"]


[workspace]
members = [ "demo_web","report/data_gen"]

[dev-dependencies]
dists = {git="https://github.com/tiby312/dists.git"}

[dependencies]
itertools = "0.10"
rayon-core = {version="1.9.0",optional=true}
compt = "^1.10.1"
axgeom = {version="1.9",default-features = false}
twounordered = "^0.6.2"
slice-group-by = "0.3"

[package.metadata.docs.rs]
# This sets the default target to `x86_64-unknown-linux-gnu`
# and only builds that target
targets = ["x86_64-unknown-linux-gnu"]

#  when using flamegraph
# [profile.release]
# debug = true

