[package]
name = "broccoli"
version = "1.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
description = "broadphase collision detection algorithms"
license = "MIT"
repository = "https://github.com/tiby312/broccoli"
keywords = ["tree", "kdtree","broadphase","space-partitioning","no_std"]
readme = "README.md"
edition = "2018"
include = ["src/**/*", "LICENSE-MIT", "README.md"]

[features]
default = ["use_rayon"]
use_rayon = ["rayon"]


[workspace]
members = [ "demo","report/data_gen"]

[dev-dependencies]
dists = {git="https://github.com/tiby312/dists.git"}

[dependencies]
is_sorted = "0.1"
itertools = "0.9"
rayon = {version="1.5",optional=true}
compt = "1.10"
axgeom = {version="1.9",default-features = false}
pdqselect = "0.1"
twounordered = "0.6.0"

[package.metadata.docs.rs]
# This sets the default target to `x86_64-unknown-linux-gnu`
# and only builds that target
targets = ["x86_64-unknown-linux-gnu"]
