[package]
name = "broccoli"
version = "2.2.1"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
description = "broadphase collision detection algorithms"
license = "MIT"
repository = "https://github.com/tiby312/broccoli"
keywords = ["tree", "kdtree","broadphase","space-partitioning","no_std"]
readme = "README.md"
edition = "2018"
include = ["src/**/*", "LICENSE-MIT", "README.md"]


[lib]
doctest = false

[workspace]
members = [ "broccoli-tree","demo-web","report/data_gen","broccoli-ext"]

[dev-dependencies]
dists = {git="https://github.com/tiby312/dists.git"}

[dependencies]
broccoli-tree={path="broccoli-tree"}
rayon-core="*"
itertools = "0.10"
compt = "2.0"
axgeom = {version="1.9",default-features = false}
twounordered = "0.7"
slice-group-by = "0.3"
revec = "0.2"

[package.metadata.docs.rs]
# This sets the default target to `x86_64-unknown-linux-gnu`
# and only builds that target
targets = ["x86_64-unknown-linux-gnu"]

#  when using flamegraph
# [profile.release]
# debug = true

