[package]
name = "demo-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
broccoli={path="../"}
poloto="*"
dists={git="https://github.com/tiby312/dists"}
