[package]
name = "not-sorted"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
broccoli={path="../../broccoli"}
broccoli-rayon={path="../../broccoli-rayon"}
compt="2.1"